name: nyalock-cron

on:
  schedule:
    # JST 01:00 = 16:00 UTC (前日)
    - cron: '0 16 * * *'
    # JST 13:00 = 04:00 UTC
    - cron: '0 4 * * *'
    # JST 14:00 = 05:00 UTC
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  ingest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -q openai requests playwright beautifulsoup4 lxml
          python -m playwright install --with-deps chromium

      - name: Run ingest and transcription
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ZOOM_CLIENT_ID: ${{ secrets.ZOOM_CLIENT_ID }}
          ZOOM_CLIENT_SECRET: ${{ secrets.ZOOM_CLIENT_SECRET }}
        run: |
          echo "Starting nyalock ingest at JST:" $(date)
          
          # 実際の文字起こし処理を実行
          python real_transcription_extractor.py
          
          # OpenAI APIキーが設定されていればWhisper版も実行
          if [ -n "$OPENAI_API_KEY" ]; then
            echo "Running Whisper transcription..."
            python whisper_transcription.py
          fi
          
          # 生成されたファイルをdocs/nyalockディレクトリに配置
          mkdir -p docs/nyalock
          
          # 生成物をコピー（存在する場合のみ）
          [ -f real_transcriptions.json ] && cp real_transcriptions.json docs/nyalock/
          [ -f real_transcriptions.txt ] && cp real_transcriptions.txt docs/nyalock/
          [ -f whisper_transcriptions.json ] && cp whisper_transcriptions.json docs/nyalock/
          [ -f whisper_transcriptions.txt ] && cp whisper_transcriptions.txt docs/nyalock/
          
          echo "Ingest completed at JST:" $(date)

      - name: Commit artifacts (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore(cron): scheduled ingest (JST)"
          git push || true
